### ISSUE TITLE
wrong link in the output html for the twenty sixteen sample

### ISSUE THREAD

**Issue by mbuccarello** [digexp/Sample-WordPressThemeConverter#1]
In the image below when I click to the here link  I get a 404 error ( not found page )

![image](https://cloud.githubusercontent.com/assets/10175049/14777144/82a042d2-0acb-11e6-89bc-35c468b54761.png)

Link : https://developer.ibm.com/digexp/docs/docs/themes/creating-an-ibm-digital-experience-v8-5-theme-from-a-twentysixteen-theme/#js

Error

![image](https://cloud.githubusercontent.com/assets/10175049/14777190/d76e383c-0acb-11e6-8220-437f78261d75.png)

**Comment by llpomerl** [comment]
Thanks, see commit 8a521d8 for a fix.
