### ISSUE TITLE
problems to apply manual steps 

### ISSUE THREAD

**Issue by mbuccarello** [digexp/Sample-WordPressThemeConverter#2]
Hi,

I follow and documented all the steps used in my test env to configure and install **Sample-WordPressThemeConverter** and the generated PAA  **TwentySixteen Theme** .

Now I don't clearly understand how to manipulate the theme.html and the skin.html file.

I tried to follow your guide to manually modify theme and skin but the result was always the same a black page.

The navigation.jsp works fine.

All moduled are loaded correctly.

Another thing to consider are the missing images in the css folder as described in the output html file in the next steps section.

Another strange thing to check is theme.html automatically generated have inside the lm:template directive, why? This normaly could be stay in the skin.html.
##### section added to the generated theme.html

<!DOCTYPE html>
<html lang="en" >
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1">
<meta http-equiv="X-UA-Compatible" content="IE=Edge">

<link rel="dynamic-content" href="co:head">

</head>
<body id="content" >    
###### 
###### section added to the skin.html

I cut it from the theme html !!!!!

```
<div id="primary" class="content-area">
    <main id="main" class="site-main" role="main">

    <a rel="dynamic-content" href="lm:template"></a>

    </main><!-- .site-main -->
</div><!-- .content-area -->
```
###### 

some screen
skin.html
![image](https://cloud.githubusercontent.com/assets/10175049/14779454/87749576-0ad8-11e6-885a-564a520bd912.png)
theme.html
![image](https://cloud.githubusercontent.com/assets/10175049/14779482/9e95e25a-0ad8-11e6-8883-077fa20b5621.png)

theme.html after my first manipulation ( I know there are some php call insde )

![image](https://cloud.githubusercontent.com/assets/10175049/14779516/ba08d0a6-0ad8-11e6-8158-b6b043a9d762.png)

**Comment by mbuccarello** [comment]
These are all the steps I used to setup my environment.

[wp_theme.zip](https://github.com/digexp/Sample-WordPressThemeConverter/files/234243/wp_theme.zip)

**Comment by llpomerl** [comment]
The lm:template dynamic content spot should be inside theme.html. It is used to call out to the layout template, and in this case is a replacement for The Loop code. The skin.html file should have references to lm:control, which calls out to the portlet contents, and possibly lm:title, depending on the input WordPress theme.

**Comment by llpomerl** [comment]
Your setup steps from the zip look good.

**Comment by mbuccarello** [comment]
what are the next steps to have a fully functional theme?

Because simply remove php code and add co:head doesn't work for me

**Comment by llpomerl** [comment]
A few things:
- theme.html should have lm:template
- skin.html should have lm:control
- theme.html should have co:head and co:config
- php code should be examined to see if it should be removed or replaced with appropriate Portal code, there are lists of what can be removed and replaced in my [original article](https://developer.ibm.com/digexp/docs/docs/themes/creating-an-ibm-digital-experience-v8-5-theme-from-a-wordpress-theme/)
- check for errors in the logs and the javascript console
- Keep in mind the final theme will not look exactly like the twenty sixteen theme, nor have all the functionality, as the theme is being transferred from one product to another. The new portal theme will be a simplified version of the WordPress theme, that is meant to give a head start for developers over starting from scratch.

**Comment by mbuccarello** [comment]
Hi Laura,

it is possible to share a finished TwentySixteen Theme ?

Thanks 

Michele.

**Comment by llpomerl** [comment]
Please see my latest commit. It includes sample html and paa output for the twentysixteen theme.
